inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "Gemfile"
    - "spec/spec_helper.rb"
    - "vendor/**/*"

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false